const cases={
"log-splitter":{label:"MECHANICAL DESIGN CASE STUDY",title:"25-Ton Hydraulic Log Splitter",image:"log-splitter-hero.jpg",summary:"A complete towable log-splitter design integrating hydraulic power, structural steel fabrication, component selection, detailed engineering analysis and operator safety.",blocks:[['Challenge','Create a robust and manufacturable system capable of producing a 25-ton splitting force while remaining towable, maintainable and safe.'],['Engineering approach','Sized the cylinder, two-stage pump, gasoline engine, reservoir, control valve and hose network, then designed the structural frame and mounting details around those components.'],['Validation','Completed beam, wedge, weld, bolt, pin, tipping and hydraulic-performance calculations, supported by finite-element analysis.'],['Deliverables','3D assembly, component layouts, fabrication drawings, engineering calculations, purchased-parts list and full technical report.']],tags:['Autodesk Inventor','Mathcad','FEA','Hydraulics','Structural design','Engineering drawings'],report:'Log_Splitter_Technical_Report.pdf',reportLabel:'View technical report'},
whiteboard:{label:"ROBOTICS PROJECT",title:"ABB Robot Whiteboard Writing",image:"whiteboard-thumb.jpg",summary:"An automated writing-and-erasing sequence built around precise robot targets, coordinate systems and digital I/O.",blocks:[['Sequence','On pushbutton input, the robot writes “MUHIGA,” draws a smiley, waits four seconds, erases the writing and returns to its ready position.'],['Programming','Created individual target groups for each letter, approach and departure points, plus a separate set of erase targets.'],['Control','Integrated a momentary pushbutton input and green pilot-light output to create a clear operator-controlled cycle.'],['Key learning','The main challenge was positioning the character geometry accurately relative to the user coordinate system.']],tags:['ABB RobotStudio','RAPID','Motion planning','Digital I/O','Coordinate systems']},
palletizing:{label:"AUTOMATION PROJECT",title:"ABB Robotic Palletizing System",image:"palletizing-thumb.jpg",summary:"A configurable robot cell that transfers cylindrical components between a conveyor and a 5 × 4 pallet array.",blocks:[['Operation','The cell can load the pallet from the conveyor or unload selected pallet positions back to the conveyor.'],['Flexible indexing','Used a base target and calculated offsets so one reference position could generate the complete 20-position pallet pattern.'],['End-of-arm tooling','Designed and fabricated gripper fingers suited to handling the cylindrical workpieces.'],['Control logic','Integrated gripper actuation and closed-state verification into the robot sequence.']],tags:['ABB','RAPID','Array indexing','Custom gripper','Digital I/O','Palletizing']},
mastercam:{label:"CNC PROCESS CASE STUDY",title:"Mastercam Milling Process",image:"mastercam-finished.jpg",summary:"A full CNC milling workflow from geometry and stock setup through simulation, NC generation, machining and dimensional verification.",blocks:[['Process planning','Created the part geometry, defined stock and developed the required milling operations in Mastercam.'],['Verification','Used backplot and solid verification to review tool motion, material removal and potential errors before machining.'],['Problem solving','A circle-milling operation generated excessive tool load and jammed. The strategy was replaced with a helical-bore operation to reduce plunging forces.'],['Result','Completed the machined component and documented observations, corrections and dimensional inspection.']],tags:['Mastercam','Tormach 440','CAM','Toolpaths','NC code','Inspection']},
shaft:{label:"CNC TURNING PROJECT",title:"Tapered Stepped Shaft",image:"cnc-shaft-thumb.jpg",summary:"A manually programmed CNC turning project producing multiple diameters, shoulders and a tapered profile in Aluminum 2011-T3.",blocks:[['Planning','Defined the machining sequence, tool calls and safe approach/retract positions for the stepped geometry.'],['Programming','Created the turning program manually using G-code rather than relying on a CAM-generated program.'],['Setup','Established work and tool offsets and controlled axial lengths, diameters and taper geometry.'],['Demonstration','The accompanying video documents the cutting cycle and progression of the finished profile.']],tags:['Manual G-code','CNC lathe','Turning','Taper machining','Offsets','Aluminum 2011-T3']},
hydraulics:{label:"FLUID POWER ANALYSIS",title:"Hydraulic Cylinder Circuit Analysis",image:"hydraulic-extension.jpg",summary:"A system-level analysis of a double-acting hydraulic cylinder during full-load extension and retraction.",blocks:[['Circuit','The system includes a fixed-displacement pump, electric motor, directional control valve, pressure relief valve, gauge, filter, reservoir and double-acting cylinder.'],['Extension','Pump flow is directed to the cap end. The larger piston area creates the extension force while rod-end oil returns through the valve and filter to tank.'],['Retraction','The valve reverses the connections, directing flow to the rod end while cap-end oil returns to the reservoir. Because the annular area is smaller, retract speed and force differ from extension.'],['Analysis','Evaluated pressure, flow, cylinder speed, generated force, motor power, pump output and return-flow behaviour under load.']],tags:['Fluid power','Double-acting cylinder','DCV','Relief valve','Flow analysis','Power calculations']}
};
const videoDialog=document.querySelector('#videoDialog'),caseDialog=document.querySelector('#caseDialog'),video=document.querySelector('#projectVideo'),videoTitle=document.querySelector('#videoTitle'),caseContent=document.querySelector('#caseContent');
document.querySelectorAll('[data-video]').forEach(btn=>btn.addEventListener('click',()=>{video.src=btn.dataset.video;video.title=btn.dataset.title;videoTitle.textContent=btn.dataset.title;videoDialog.showModal();document.body.classList.add('locked');}));
document.querySelectorAll('[data-case]').forEach(btn=>btn.addEventListener('click',()=>{const c=cases[btn.dataset.case];caseContent.innerHTML=`<p class="dialog-label">${c.label}</p><h2>${c.title}</h2><p>${c.summary}</p><div class="case-hero-wrap"><img class="case-hero" src="${c.image}" alt="${c.title}">${c.report?`<a class="btn primary case-report-btn" href="${c.report}" target="_blank" rel="noopener">${c.reportLabel||'View project report'} ↗</a>`:''}</div><div class="case-grid">${c.blocks.map(b=>`<div class="case-block"><span>${b[0].toUpperCase()}</span><h3>${b[0]}</h3><p>${b[1]}</p></div>`).join('')}</div><div class="case-tags">${c.tags.map(t=>`<span>${t}</span>`).join('')}</div>`;caseDialog.showModal();document.body.classList.add('locked');}));
document.querySelectorAll('dialog .close').forEach(btn=>btn.addEventListener('click',()=>btn.closest('dialog').close()));
document.querySelectorAll('dialog').forEach(d=>{d.addEventListener('click',e=>{if(e.target===d)d.close()});d.addEventListener('close',()=>{document.body.classList.remove('locked');if(d===videoDialog){video.removeAttribute('src');}})});
const io=new IntersectionObserver(entries=>entries.forEach(e=>{if(e.isIntersecting){e.target.classList.add('visible');io.unobserve(e.target)}}),{threshold:.12});document.querySelectorAll('.reveal').forEach(el=>io.observe(el));
const progress=document.querySelector('#progressBar');addEventListener('scroll',()=>{const h=document.documentElement.scrollHeight-innerHeight;progress.style.width=`${h>0?scrollY/h*100:0}%`});
document.querySelector('#year').textContent=new Date().getFullYear();
const menuToggle=document.querySelector('#menuToggle'),nav=document.querySelector('#siteNav');menuToggle.addEventListener('click',()=>{const open=nav.classList.toggle('open');menuToggle.setAttribute('aria-expanded',open);});nav.querySelectorAll('a').forEach(a=>a.addEventListener('click',()=>nav.classList.remove('open')));
